// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Infrastructure;

#nullable disable

namespace Project.Infrastructure.Migrations
{
    [DbContext(typeof(employeeDetailsContext))]
    [Migration("20251125120543_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project.Domain.EmployeeDetails", b =>
                {
                    b.Property<Guid>("emNo")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EmployeeNumber");

                    b.Property<string>("empIdNum")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("EmployeeIDNumber");

                    b.Property<string>("empName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EmployeeName");

                    b.Property<string>("empSurname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EmployeeSurName");

                    b.HasKey("emNo");

                    b.ToTable("EmployeeDetails", (string)null);
                });

            modelBuilder.Entity("Project.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("code")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Code");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasAnnotation("Relational:JsonPropertyName", "AccountNumber");

                    b.Property<decimal>("Balance")
                        .HasMaxLength(12)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Balance");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PersonalDetailCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PersonalId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("code");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("PersonalDetailCode");

                    b.HasIndex("PersonalId")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("Project.Domain.Entities.Login", b =>
                {
                    b.Property<Guid>("loginId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LoginId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Username");

                    b.HasKey("loginId");

                    b.ToTable("Login", (string)null);
                });

            modelBuilder.Entity("Project.Domain.Entities.PersonalDetail", b =>
                {
                    b.Property<Guid>("Code")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Code");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateOfBirth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FirstName");

                    b.Property<string>("IDNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("IDNumber");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LastName");

                    b.HasKey("Code");

                    b.ToTable("PersonalDetail", (string)null);
                });

            modelBuilder.Entity("Project.Domain.Entities.Transactions", b =>
                {
                    b.Property<Guid>("code")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("code");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AccountId");

                    b.Property<string>("Descriptiion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Descriptiion");

                    b.Property<decimal>("Outstanding_Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Outstanding_Amount");

                    b.Property<Guid?>("PersonalDetailCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("TransactionDate");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TransactionType");

                    b.HasKey("code");

                    b.HasIndex("AccountId");

                    b.HasIndex("PersonalDetailCode");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("Project.Domain.Entities.Account", b =>
                {
                    b.HasOne("Project.Domain.Entities.PersonalDetail", "PersonalDetail")
                        .WithMany("Accounts")
                        .HasForeignKey("PersonalDetailCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalDetail");
                });

            modelBuilder.Entity("Project.Domain.Entities.Transactions", b =>
                {
                    b.HasOne("Project.Domain.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.PersonalDetail", null)
                        .WithMany("Transactions")
                        .HasForeignKey("PersonalDetailCode");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Project.Domain.Entities.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Project.Domain.Entities.PersonalDetail", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
